CREATE EVENT AUTOMATION_NUMBEO 
ON SCHEDULE EVERY 1 DAY
STARTS '2023-04-04 14:15:00'
DO
	DROP DATABASE IF EXISTS WEBSCRAPPING;
	CREATE DATABASE WEBSCRAPPING;

	USE WEBSCRAPPING;

	DROP DATABASE IF EXISTS CITIES;

	CREATE TABLE CITIES
	(
	RANK_ INT NOT NULL,
	CITY VARCHAR(50) PRIMARY KEY,
	COST_OF_LIVING_INDEX REAL,
	RENT_INDEX REAL,
	COST_OF_LIVING_PLUS_RENT_INDEX REAL,
	GROCERY_INDEX REAL,
	RESTAURANT_PRICE_INDEX REAL,
	LOCAL_PURCHASING_POWER_INDEX REAL 
	);

	SELECT * FROM CITIES;

	DROP TABLE IF EXISTS UPDATE_DATA;

	CREATE TABLE UPDATE_DATA
	(
	CITY VARCHAR(50),
	DATE DATETIME
	);

	SELECT * FROM UPDATE_DATA;

	DROP TABLE IF EXISTS RESTAURANT_COST_TEST;

	CREATE TABLE RESTAURANT_COST_TEST
	(
	CITY VARCHAR(50),
	RESTAURANTS varchar(255),
	AMOUNT REAL
	);

	SELECT * FROM RESTAURANT_COST_TEST;

	DROP TABLE IF EXISTS MARKET_COST_SET;

	CREATE TABLE MARKET_COST_SET
	(
	CITY VARCHAR(50),
	MARKET TEXT,
	AMOUNT REAL
	);

	SELECT * FROM MARKET_COST_SET;

	DROP TABLE IF EXISTS TRANSPORTATION_COST_STATUS;

	CREATE TABLE TRANSPORTATION_COST_STATUS
	(
	CITY VARCHAR(50),
	MARKET TEXT,
	AMOUNT REAL
	);

	SELECT * FROM TRANSPORTATION_COST_STATUS;

	DROP TABLE IF EXISTS UTILIES_COST_SET;

	CREATE TABLE UTILIES_COST_SET
	(
	CITY VARCHAR(50),
	UTILITIES_MONTHYLY TEXT,
	AMOUNT REAL
	);

	SELECT * FROM UTILIES_COST_SET;

	DROP TABLE IF EXISTS SPPORTS_LEISURE_COST_SET;

	CREATE TABLE SPPORTS_LEISURE_COST_SET
	(
	CITY VARCHAR(50),
	SPORTS_AND_LEISURE TEXT,
	AMOUNT REAL
	);

	SELECT * FROM SPPORTS_LEISURE_COST_SET;

	DROP TABLE IF EXISTS CHILDCARE;

	CREATE TABLE CHILDCARE
	(
	CITY VARCHAR(50),
	CHILDCARE TEXT,
	AMOUNT REAL
	);

	SELECT * FROM CHILDCARE;

	DROP TABLE IF EXISTS CLOTHING_SHOES_COST_SET;

	CREATE TABLE CLOTHING_SHOES_COST_SET
	(
	CITY VARCHAR(50),
	CLOTHING_AND_SHOES TEXT,
	AMOUNT REAL
	);

	SELECT * FROM CLOTHING_SHOES_COST_SET;

	DROP TABLE IF EXISTS RENT_COST_SET;

	CREATE TABLE RENT_COST_SET
	(
	CITY VARCHAR(50),
	RENT_PER_MONTH TEXT,
	AMOUNT REAL
	);

	SELECT * FROM RENT_COST_SET;

	DROP TABLE IF EXISTS BUY_APT_COST_SET;

	CREATE TABLE BUY_APT_COST_SET
	(
	CITY VARCHAR(50),
	BUY_APARTMENT_PRICE TEXT,
	AMOUNT REAL
	);

	SELECT * FROM BUY_APT_COST_SET;

	DROP TABLE IF EXISTS SALARY_AND_FINANCING_COST;

	CREATE TABLE SALARY_AND_FINANCING_COST
	(
	CITY VARCHAR(50),
	SALARIES_AND_FINANCING TEXT,
	AMOUNT REAL
	);	


	SELECT * FROM SALARY_AND_FINANCING_COST; 